"""migracion de las tablas

Revision ID: b3b61591bbb0
Revises: 
Create Date: 2025-01-07 03:30:28.346528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b61591bbb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('benefits', sa.String(length=255), nullable=False),
    sa.Column('measure', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_proteins', sa.Float(), nullable=False),
    sa.Column('total_fats', sa.Float(), nullable=False),
    sa.Column('total_carbohydrates', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('PAL', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('url_image', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('health_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('health_restrictions', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('physical_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['physical_activity_id'], ['physical_activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meal_food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('type_quantity', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutritionist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('date_generation', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('other_objetive', sa.String(length=255), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('number_days', sa.Integer(), nullable=False),
    sa.Column('health_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_meal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_meal')
    op.drop_table('health_objective')
    op.drop_table('plan')
    op.drop_table('nutritionist')
    op.drop_table('meal_food')
    op.drop_table('health_profile')
    op.drop_table('user')
    op.drop_table('physical_activity')
    op.drop_table('meal')
    op.drop_table('food')
    # ### end Alembic commands ###
